<?php include "header.phtml"?>
    <main id="categorie">
   <section class="section-container" >
            <h2 class="title">À propos</h2>
           
                        <div class="Container " style="margin : 60px 0;" >
                               <h3>
                                Ce site a été realisé exclusivement pour la 3W ACADEMY afin de
                                valider mon diplôme et je n'ai aucune intention de le lancer comme projet commercial
                               </h3>
                            
                        </div>
                   
        </section>
    </main>
    <?php include "footer.phtml"?>