<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Major+Mono+Display|Saira+Extra+Condensed" rel="stylesheet">     <link rel="stylesheet" href="assets/css/normalize.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/tablette.css">
    <link rel="stylesheet" href="assets/css/mobile.css">
    <title>Code Shop</title>
    <script type="module" src="assets/js/main.js"></script>

</head>
<body>
<header>
    <nav>
        <i class="fas fa-bars"></i>
        <a class="shop-mobile" href="index?page=panier">
            <i class="fas fa-shopping-cart "></i>
            <?php if(isset( $_SESSION['panier']["quantiteGlobal"])) : ?>
            <span><?= $_SESSION['panier']["quantiteGlobal"]?></span>
            <?php endif; ?>
        </a>

        <ul >
            <li><a href="index">Home</a></li>
            <li><a href="index?page=apropos">A propos</a></li>
            <?php if(isset($_GET["page"] )): ?>
            <li><a href="index" class="search-icon"> <i class="fas fa-search"></i></a></li>
            <?php endif; ?>
        </ul>
       <ul>
           <li>
                <a class="shop" href="index?page=panier">
                    <i class="fas fa-shopping-cart "></i>
                    <?php if(isset( $_SESSION['panier']["quantiteGlobal"])) : ?>
                    <span><?= $_SESSION['panier']["quantiteGlobal"]?></span>
                    <?php endif; ?>
                </a>
           </li>
           <?php if(isset($_SESSION["user"]["email"])) : ?>
           <div>
                <span class="userAdmin">
                <li> <?=$_SESSION["user"]["email"]?></li>
                    <div>
                        <li><a href="index?page=mesCommandes"><small>Mes Commandes</small></a></li>
                        <li><a href="index?page=log_out"><small>Se déconnecter</small></a></li>
                    </div>
                
                </span>

           </div>
                
           <?php else : ?>
           <li><a href="index?page=login">Connexion</a></li>
           <li><a href="index?page=inscription">Inscription</a></li>
            <?php endif; ?>

       </ul> 

    </nav>
    <nav>
        <ul>
            <?php if(isset($_SESSION["categorie"])): foreach($_SESSION["categorie"] as $categorie): ?>
                <li><a href="index?page=categorie&id=<?=$categorie['id']?>"><?=$categorie["titre"] ?></a></li>
            <?php endforeach; endif;?>
        </ul>
    </nav>
</header>

